/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ibxSoXtBGpQJ21i2zn1Jd7
// Component: _SROjryz8RTr

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { StrapiField } from "@plasmicpkgs/plasmic-strapi";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: ibxSoXtBGpQJ21i2zn1Jd7/projectcss
import sty from "./PlasmicTweetCard.module.css"; // plasmic-import: _SROjryz8RTr/css

createPlasmicElementProxy;

export type PlasmicTweetCard__VariantMembers = {};
export type PlasmicTweetCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicTweetCard__VariantsArgs;
export const PlasmicTweetCard__VariantProps = new Array<VariantPropType>();

export type PlasmicTweetCard__ArgsType = {};
type ArgPropType = keyof PlasmicTweetCard__ArgsType;
export const PlasmicTweetCard__ArgProps = new Array<ArgPropType>();

export type PlasmicTweetCard__OverridesType = {
  root?: Flex__<"div">;
  tweetTitle?: Flex__<typeof StrapiField>;
  tweetDescr?: Flex__<typeof StrapiField>;
};

export interface DefaultTweetCardProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTweetCard__RenderFunc(props: {
  variants: PlasmicTweetCard__VariantsArgs;
  args: PlasmicTweetCard__ArgsType;
  overrides: PlasmicTweetCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root
      )}
    >
      <StrapiField
        data-plasmic-name={"tweetTitle"}
        data-plasmic-override={overrides.tweetTitle}
        className={classNames("__wab_instance", sty.tweetTitle)}
        path={"t_title"}
      />

      <StrapiField
        data-plasmic-name={"tweetDescr"}
        data-plasmic-override={overrides.tweetDescr}
        className={classNames("__wab_instance", sty.tweetDescr)}
        path={"t_content"}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "tweetTitle", "tweetDescr"],
  tweetTitle: ["tweetTitle"],
  tweetDescr: ["tweetDescr"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  tweetTitle: typeof StrapiField;
  tweetDescr: typeof StrapiField;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTweetCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTweetCard__VariantsArgs;
    args?: PlasmicTweetCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTweetCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTweetCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTweetCard__ArgProps,
          internalVariantPropNames: PlasmicTweetCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTweetCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTweetCard";
  } else {
    func.displayName = `PlasmicTweetCard.${nodeName}`;
  }
  return func;
}

export const PlasmicTweetCard = Object.assign(
  // Top-level PlasmicTweetCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tweetTitle: makeNodeComponent("tweetTitle"),
    tweetDescr: makeNodeComponent("tweetDescr"),

    // Metadata about props expected for PlasmicTweetCard
    internalVariantProps: PlasmicTweetCard__VariantProps,
    internalArgProps: PlasmicTweetCard__ArgProps
  }
);

export default PlasmicTweetCard;
/* prettier-ignore-end */
